In [1]:
%matplotlib inline
import numpy as np
from scipy.stats import multivariate_normal
from scipy.linalg import pinv

# Set the number of observations (N), number of dependent variables (k), and number of independent variables (p)
N = 1000
k = 3
p = 2

# Mean vector and covariance matrix for the multivariate normal distribution
mu = [0] * k
Sigma = [[1, 0.5, 0], [0.5, 2, 0], [0, 0, 3]]

# Define the multivariate normal distributions for T and u
T_distribution = multivariate_normal(mean=mu, cov=Sigma)
u_distribution = multivariate_normal(mean=np.zeros(k), cov=np.eye(k) * 0.2)

# Generate samples for T and u
T_sample = T_distribution.rvs(size=N)
u_sample = u_distribution.rvs(size=N)  # u is now N x k

# Generate a random matrix D for the dependency of X on T
D = np.random.rand(k, p)

# Generate the design matrix X (non-linear dependence on T)
X = np.power(T_sample, 3) @ D

# Generate the true beta coefficients for simulation purposes
beta_true = np.array([[0.5], [1]])

# Generate the response matrix y (since we have k variables)
y = X @ beta_true + u_sample

In [2]:
# Now let's estimate the beta coefficients using the simulated data (X, y)

# We will use the np.linalg.lstsq function to estimate beta
# This function solves the equation a x = b by computing a vector x that minimizes the Euclidean 2-norm || b - a x ||^2
beta_estimated, residuals, rank, s = np.linalg.lstsq(X, y, rcond=None)

# Print the estimated beta coefficients
print("Estimated beta coefficients:\n", beta_estimated)

Estimated beta coefficients:
 [[0.50124262 0.49704119 0.50122804]
 [0.99909286 0.99926705 1.00212098]]


In [3]:
# Calculate the residuals as the difference between the observed and predicted y
residuals = y - X @ beta_estimated

# Calculate the variance of the residuals
residual_var = residuals.var(ddof=1)  # ddof=1 provides an unbiased estimator by dividing by N-1

# Calculate and print the covariance matrix of the estimated beta coefficients
cov_beta = residual_var * np.linalg.inv(X.T @ X)
print("Covariance matrix of estimated beta coefficients:\n", cov_beta)

Covariance matrix of estimated beta coefficients:
 [[ 3.61988050e-06 -5.08930921e-07]
 [-5.08930921e-07  1.74038712e-06]]
