## Exercise 5

In [14]:
import numpy as np
from scipy.stats import multivariate_normal
from scipy.linalg import pinv
import random
random.seed(123)

First we generate the distribution of $T$ and $u$.

In [31]:
# Set the number of observations (N), number of dependent variables (k), and number of independent variables (p)
k = 3
m = 4
p = 2

# Mean vector and covariance matrix for the multivariate normal distribution
mu = [0] * m
Sigma = [[1, 0.5, 0, 0],
         [0.5, 2, 0, 1],
         [0, 0, 3, 0],
        [0, 0, 0, 1]]

# Define the multivariate normal distributions for T and u
T_distribution = multivariate_normal(mean=mu, cov=Sigma)
u_distribution = multivariate_normal(mean=np.zeros(k), cov=np.eye(k) * 0.2)

We genenrate $X$ as $X=T^3D + uD'$, where $D$ is an $m\times p$ matrix, $D'$ is an $k\times p$ matrix.

In [32]:
# observations realization
N = 1000

# Generate samples for T and u
T = T_distribution.rvs(size=N)
u = u_distribution.rvs(size=N)  # u is now N x k

# Generate a random matrix D for the dependency of X on T
D = np.random.rand(m,p)
D1 = np.random.rand(k,p)

# Generate the design matrix X (non-linear dependence on T)
X = np.power(T, 3) @ D + u @ D1

# Generate the true beta coefficients for simulation purposes
beta_true = np.array([[0.5,2,1.5], [1,0.5,3]])

# Generate the response matrix y (since we have k variables)
y = X @ beta_true + u

In [33]:
# estimate 
b = np.linalg.lstsq(T.T@X,T.T@y,rcond=None)[0]

# Print the estimated beta coefficients
print("Estimated beta coefficients:\n", b)

Estimated beta coefficients:
 [[0.50319339 1.99808012 1.49934221]
 [0.9862687  0.50932679 3.00657509]]


In [52]:
e = y - X@b

TXplus = np.linalg.pinv(T.T@X) # Moore-Penrose pseudo-inverse

# Covariance matrix of b
vb = np.kron(TXplus@T.T@e,e.T@T@TXplus.T) # here we need Kronecker product

print("Covariance matrix of estimated beta coefficients:\n",vb)

Covariance matrix of estimated beta coefficients:
 [[ 2.49711363e-32 -1.05442807e-31 -1.52408259e-31  6.43557202e-31
   6.69625716e-32 -2.82755315e-31]
 [-1.51062209e-31  3.49852821e-31  9.21989611e-31 -2.13528365e-30
  -4.05088254e-31  9.38164939e-31]
 [ 6.63761362e-32  2.56323925e-31 -4.05118582e-31 -1.56444155e-30
   1.77994174e-31  6.87357955e-31]
 [-1.06286518e-31  4.48804119e-31  3.52521541e-31 -1.48855304e-30
   2.58970131e-31 -1.09352403e-30]
 [ 6.42977398e-31 -1.48910477e-30 -2.13256947e-30  4.93892845e-30
  -1.56663275e-30  3.62824621e-30]
 [-2.82521721e-31 -1.09101073e-30  9.37042574e-31  3.61856601e-30
   6.88372225e-31  2.65827872e-30]]


Hence we could still use the estimator to estimate beta, however we need to change a little bit to estimate the variance here.

## Exercise Six

In [57]:
# Set the number of observations (N), number of dependent variables (k), and number of independent variables (p)
k = 3
m = 2

# Mean vector and covariance matrix for the multivariate normal distribution
mu = [0] * m
Sigma1 = [[1, 0.5],
         [0.5, 2]]
Sigma2 = [[1, 0.5, 0],
          [0.5, 2, 0],
          [0, 0, 3]]

# Define the multivariate normal distributions for T and u
T_distribution = multivariate_normal(mean=mu, cov=Sigma1)
u_distribution = multivariate_normal(mean=np.zeros(k), cov=Sigma2)

Let $X = T$.

In [58]:
# observations realization
N = 1000

# Generate samples for T and u
T = T_distribution.rvs(size=N)
u = u_distribution.rvs(size=N)  # u is now N x k

# Generate the design matrix X
X = T

# Generate the true beta coefficients for simulation purposes
beta_true = np.array([[0.5,2,1.5], [1,0.5,3]])

# Generate the response matrix y (since we have k variables)
y = X @ beta_true + u

In [59]:
# estimate 
b = np.linalg.lstsq(T.T@X,T.T@y,rcond=None)[0]

# Print the estimated beta coefficients
print("Estimated beta coefficients:\n", b)

Estimated beta coefficients:
 [[0.43078477 1.98314783 1.57390801]
 [1.03709713 0.51429004 2.94095903]]


In [60]:
e = y - X@b

TXplus = np.linalg.pinv(T.T@X) # Moore-Penrose pseudo-inverse

# Covariance matrix of b
vb = np.kron(TXplus@T.T@e,e.T@T@TXplus.T) # here we need Kronecker product

print("Covariance matrix of estimated beta coefficients:\n",vb)

Covariance matrix of estimated beta coefficients:
 [[ 5.20404850e-32 -3.92316901e-33 -2.16449869e-31  1.63174770e-32
   2.97594477e-31 -2.24347146e-32]
 [-2.33065007e-31  8.33974694e-32  9.69377787e-31 -3.46871697e-31
  -1.33278656e-30  4.76909973e-31]
 [ 3.11808262e-31 -1.17741858e-31 -1.29689140e-30  4.89718915e-31
   1.78308132e-30 -6.73308998e-31]
 [-1.34919776e-33  1.01711789e-34  7.61333021e-32 -5.73945096e-33
  -1.12561642e-31  8.48566926e-33]
 [ 6.04242610e-33 -2.16215661e-33 -3.40965473e-31  1.22007409e-31
   5.04110978e-31 -1.80385637e-31]
 [-8.08391790e-33  3.05256670e-33  4.56163939e-31 -1.72251978e-31
  -6.74429722e-31  2.54671279e-31]]
